# Generated by Django 3.1.5 on 2021-01-16 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IDRecApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDRecApp.imagemodel'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='filepaths',
            field=models.FileField(max_length=200, upload_to='filepaths'),
        ),
    ]
