# Generated by Django 3.1.5 on 2021-01-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDRecApp', '0002_auto_20210116_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='filename',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
